version: 2
updates:
  # 1. NPM dependencies
  - package-ecosystem: "npm"
    directory: "/"  # Location of package.json
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # 2. GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"  # Root directory for GitHub Actions workflows
    schedule:
      interval: "weekly"
