name: ESLint Code Analysis

on: [push, pull_request]

permissions:
  contents: read

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-modules

      - name: Install dependencies
        run: npm install

      - name: Create reports directory
        run: mkdir -p reports

      - name: Install HTML formatter for ESLint
        run: npm install eslint-formatter-html --save-dev

      - name: Run ESLint and generate HTML report
        run: |
          npx eslint . --format node_modules/eslint-formatter-html/index.js -o reports/eslint-report.html || true

      - name: Upload ESLint HTML report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: eslint-report
          path: reports/eslint-report.html
